version: '3.7'
services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB:   n8n
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8n_password
    volumes:
      - pgdata:/var/lib/postgresql/data

  n8n:
    build:
      context: .
      args:
        DB_TYPE:     ${DB_TYPE}
        DB_POSTGRESDB_HOST:     ${DB_HOST}
        DB_POSTGRESDB_PORT:     ${DB_PORT}
        DB_POSTGRESDB_DATABASE: ${DB_DATABASE}
        DB_POSTGRESDB_USER:     ${DB_USER}
        DB_POSTGRESDB_PASSWORD: ${DB_PASSWORD}
    image: n8n-node:local
    ports:
      - "5678:5678"
    env_file:
      - .env
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - postgres

volumes:
  pgdata:
  n8n_data:
